export enum colour {
    "Black",
    "Grey",
    "White",
    "Dark purple",
    "Light purple",
    "Bright purple",
    "Dark blue",
    "Light blue",
    "Icy blue",
    "Teal",
    "Aquamarine",
    "Saturated green",
    "Dark green",
    "Moss green",
    "Bright green",
    "Olive green",
    "Dark olive green",
    "Bright yellow",
    "Yellow",
    "Dark yellow",
    "Light orange",
    "Dark orange",
    "Light brown",
    "Saturated brown",
    "Dark brown",
    "Salmon pink",
    "Bordeaux red",
    "Saturated red",
    "Bright red",
    "Dark pink",
    "Bright pink",
    "Light pink",
}

export const colourList = Object.keys(colour).filter((value) => isNaN(Number(value)));