export enum costume {
    "Panda",
    "Tiger",
    "Elephant",
    "Gladiator",
    "Gorilla",
    "Snowman",
    "Knight",
    "Astronaut",
    "Bandit",
    "Sheriff",
    "Pirate",
    "Icecream",
    "Chips",
    "Burger",
    "Soda can",
    "Balloon",
    "Candyfloss",
    "Umbrella",
    "Pizza",
    "Security",				
    "Popcorn",
    "Arms crossed",
    "Head down",
    "Nauseous",
    "Very nauseous",
    "Needs toilet",
    "Hat",
    "Hotdog",
    "Tentacle",
    "Toffee apple",
    "Donut",
    "Coffee",
    "Nuggets",
    "Lemonade",
    "Walking",
    "Pretzel",
    "Sunglasses",
    "Sujongkwa",
    "Juice",
    "Funnel cake",
    "Noodles",
    "Sausage",
    "Soup",
    "Sandwich",
    "Guest",
    "Handyman",
    "Mechanic",
    "Security guard",
}

export const costumeList = Object.keys(costume).filter((value) => isNaN(Number(value)));