export enum colour {
    "Black",
    "Grey",
    "White",
    "Dark purple",
    "Light purple",
    "Bright purple",
    "Dark blue",
    "Light blue",
    "Icy blue",
    "Dark Water",
    "Light water",
    "Saturated green",
    "Dark green",
    "Moss green",
    "Bright green",
    "Olive green",
    "Dark olive green",
    "Bright yellow",
    "Yellow",
    "Dark yellow",
    "Pastel Orange",
    "Dark orange",
    "Light brown",
    "Saturated brown",
    "Dark brown",
    "Salmon pink",
    "Bordeaux red",
    "Saturated red",
    "Bright red",
    "Dark pink",
    "Bright pink",
    "Light pink",
    "Army green",
    "Honeydew",
    "Tan",
    "Maroon",
    "Coral pink",
    "Forest green",
    "Chartreuse",
    "Hunter green",
    "Celadon",
    "Lime green",
    "Sepia",
    "Peach",
    "Periwinkle",
    "Viridian",
    "Seafoam green",
    "Violet",
    "Lavender",
    "Orange light",
    "Deep water",
    "Pastel pink",
    "Umber",
    "Beige",
    "Invisible",
    "Void",
}

export const colourList = Object.keys(colour).filter((value) => isNaN(Number(value)));