export const guestFlags: { [key in PeepFlags]: { id: string, toggle: boolean } } = {
	leavingPark: { id: "guest-editor-leaving-park", toggle: false },
	slowWalk: { id: "guest-editor-slow-walk", toggle: false },
	tracking: { id: "guest-editor-tracking", toggle: false },
	waving: { id: "guest-editor-waving", toggle: false },
	hasPaidForParkEntry: { id: "guest-editor-has-paid", toggle: false },
	painting: { id: "guest-editor-painting", toggle: false },
	photo: { id: "guest-editor-photo", toggle: false },
	wow: { id: "guest-editor-wow", toggle: false },
	litter: { id: "guest-editor-littering", toggle: false },
	lost: { id: "guest-editor-lost", toggle: false },
	hunger: { id: "guest-editor-hunger", toggle: false },
	toilet: { id: "guest-editor-toilet", toggle: false },
	crowded: { id: "guest-editor-crowded", toggle: false },
	happiness: { id: "guest-editor-happiness", toggle: false },
	nausea: { id: "guest-editor-nausea", toggle: false },
	purple: { id: "guest-editor-purple", toggle: false },
	pizza: { id: "guest-editor-pizza", toggle: false },
	explode: { id: "guest-editor-explode", toggle: false },
	rideShouldBeMarkedAsFavourite: { id: "guest-editor-ride-should-be-marked", toggle: false },
	parkEntranceChosen: { id: "guest-editor-park-entrance-chosen", toggle: false },
	contagious: { id: "guest-editor-contagious", toggle: false },
	joy: { id: "guest-editor-joy", toggle: false },
	angry: { id: "guest-editor-angry", toggle: false },
	iceCream: { id: "guest-editor-ice-cream", toggle: false },
	hereWeAre: { id: "guest-editor-here-we-are", toggle: false },
};
